In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [9]:
engine = create_engine("mssql+pyodbc://Chand\\SQLEXPRESS/AnalyticsDB?driver=ODBC+Driver+18+for+SQL+Server&trusted_connection=yes&TrustServerCertificate=yes")

In [ ]:
query = """
SELECT 
p.Name,
sum(s.SalesAmount) as Revenue
FROM
sales s
LEFT JOIN products as p ON s.ProductID = p.ProductID
GROUP BY p.Name
ORDER BY Revenue desc
"""
df_product_revenue = pd.read_sql(query, engine)
df_product_revenue.head()

In [11]:
query = """
SELECT 
c.Country,
sum(s.SalesAmount) as Revenue
FROM
sales as s
LEFT JOIN customers as c ON s.CustomerID = c.CustomerID
GROUP BY c.Country
ORDER BY Revenue desc;
"""

df_country_revenue = pd.read_sql(query, engine)
df_country_revenue.head()

          Country  Revenue
0      Montserrat  43270.0
1      Cape Verde  37163.0
2  Cayman Islands  36342.0
3           Gabon  35746.0
4           Yemen  34335.0

In [13]:
query = """ 
SELECT
c.CustomerID,
CONCAT(c.FirstName,' ', c.LastName) as CustomerName,
sum(s.SalesAmount) as Revenue
FROM
sales as s
LEFT JOIN customers as c ON s.CustomerID = c.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName
ORDER BY Revenue desc
"""

df_top_customers = pd.read_sql(query, engine)
df_top_customers.head()

   CustomerID     CustomerName  Revenue
0         117     Haley Levine  19106.0
1         614    Kerry Sanders  17707.0
2         159           Don Ho  16596.0
3         898    Frances Vance  15522.0
4         798  Lindsey Blevins  15451.0

In [ ]:
query = """ 
SELECT 
c.Country,
p.Name,
sum(s.SalesAmount) as Revenue
FROM
sales as s
LEFT JOIN products as p ON s.ProductID = p.ProductID
LEFT JOIN customers as c ON s.CustomerID = c.CustomerID
GROUP BY c.Country, p.Name
ORDER BY c.Country asc, Revenue desc
"""

df_product_country = pd.read_sql(query, engine)
df_product_country.head()

In [15]:
query = """
SELECT
DISTINCT p.Category,
sum(s.SalesAmount) as Revenue
FROM sales as s
LEFT JOIN products as p ON s.ProductID = p.ProductID
GROUP BY p.Category
ORDER BY Revenue desc
"""

df_category_sales = pd.read_sql(query, engine)
df_category_sales.head()

                Category   Revenue
0   Headphones & Earbuds  118615.0
1     Clothing & Apparel  110676.0
2         Grooming Tools  109176.0
3  Cameras & Accessories  108671.0
4         Home & Kitchen  107473.0

In [ ]:
query = """ 
SELECT
FORMAT(OrderDate, 'yyyy-MM') as YearMonth,
sum(SalesAmount) as Revenue
FROM sales
GROUP BY FORMAT(OrderDate, 'yyyy-MM')
ORDER BY YearMonth"""

df_monthly_sales = pd.read_sql(query, engine)
df_monthly_sales.head()

  YearMonth  Revenue
0   2023-06  51217.0
1   2023-08  56804.0
2   2023-12  64128.0
3   2024-11  67315.0
4   2023-07  67332.0

In [18]:
query = """ 
SELECT
DISTINCT p.Name,
sum(s.Quantity) as TotalSalesQnty,
sum(s.SalesAmount) as Revenue
FROM
sales as s
LEFT JOIN products as p ON s.ProductID = p.ProductID
GROUP BY p.Name
ORDER BY Revenue desc
"""

df_product_sales = pd.read_sql(query, engine)
df_product_sales.head()

                           Name  TotalSalesQnty  Revenue
0                         Radio              51  40467.0
1  Automatic Headphones Stove X              31  27497.0
2        Wireless Vacuum Cooler              30  25620.0
3                        Heater              28  24559.0
4       Camera Treadmill Heater              27  24489.0